# Generated by Django 2.0.7 on 2018-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(help_text='Enter a category id (e.g. 1)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a category (e.g. python)', max_length=100, unique=True),
        ),
    ]
