# Generated by Django 2.0.7 on 2019-03-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180728_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['posted_time']},
        ),
    ]
